- name: Feeds
  columns:
    - size: small
      widgets:
        - $include: ../widgets/steam-top-sellers.yml
        - $include: ../widgets/epic-free-widget.yml
    - size: full
      widgets:
        - type: search
          search-engine: google
        - type: group
          widgets:
            - type: reddit
              subreddit: homelab
              show-thumbnails: true
            - type: reddit
              subreddit: Stremio_France
              show-thumbnails: true
    - size: small
      widgets:
        - type: weather
          units: metric
          hour-format: 24h
          location: Miramas, France
        - type: calendar
          first-day-of-week: monday
