- name: Homelab
  columns:
    - size: small
      widgets:
        $include: ../widgets/proxmox.yml
        $include: ../widgets/scrutiny.yml

    - size: full
      widgets:
        $include: ../widgets/monitors.yml
        $include: ../widgets/proxmox-detailed-resources.yml

    - size: small
      widgets:
        $include: ../widgets/bookmarks.yml
        $include: ../widgets/tailscale.yml
        $include: ../widgets/immich-stats.yml
