- type: monitor
  cache: 1m
  title: Hardware
  sites:
    - title: Proxmox
      url: https://proxmox.legoatdesserveurs.fr/
      check-url: https://${PROXMOX_URL}
      icon: di:proxmox
      allow-insecure: true
    - title: NFS
      url: http://192.168.1.147:9090
      icon: https://www.elevenforum.com/data/attachments/42/42324-06f4252c57398584e53c9dc52040e641.jpg

- type: monitor
  cache: 1m
  title: Web Services
  sites:
    - title: Adguard Home
      url: https://adguard.legoatdesserveurs.fr/
      check-url: http://192.168.1.95/
      icon: sh:adguard-home
    - title: Nginx Proxy Manager
      url: https://npm.legoatdesserveurs.fr/
      check-url: http://192.168.1.110:81
      icon: di:nginx-proxy-manager
    - title: Dokploy
      url: https://dokploy.legoatdesserveurs.fr/
      check-url: http://192.168.1.149:3000/
      icon: sh:dokploy
    - title: Glance
      url: https://legoatdesserveurs.fr/
      check-url: http://192.168.1.149:9998/
      icon: sh:glance
    - title: Scrutiny
      url: https://scrutiny.legoatdesserveurs.fr/
      check-url: http://192.168.1.149:8087/
      icon: di:scrutiny

- type: docker-containers
  hide-by-default: true
  containers:
    enshrouded-enshrouded-cimqmp-enshrouded-1:
      name: Enshrouded Dedicated Server
      icon: https://enshrouded.wiki.gg/images/Site-logo.png
      hide: false
    any-sync-dockercompose-any-sync-filenode-1:
      name: Anytype
      icon: si:anytype
      hide: false
