- type: monitor
  cache: 1m
  title: Hardware
  sites:
    - title: PVE
      url: https://pve.kipavy.fr/
      check-url: https://${PROXMOX_URL}
      icon: di:proxmox
      allow-insecure: true
    - title: PBS
      url: https://pbs.kipavy.fr/
      icon: di:proxmox
      allow-insecure: true
    - title: NFS
      url: https://192.168.1.78:9090
      icon: https://www.elevenforum.com/data/attachments/42/42324-06f4252c57398584e53c9dc52040e641.jpg
      allow-insecure: true

- type: monitor
  cache: 1m
  title: Web Services
  sites:
    - title: Adguard Home
      url: https://adguard.kipavy.fr/
      check-url: http://192.168.1.95/
      icon: sh:adguard-home
    - title: Nginx Proxy Manager
      url: https://npm.kipavy.fr/
      check-url: https://192.168.1.110:81
      icon: di:nginx-proxy-manager
      allow-insecure: true
    - title: Dokploy
      url: https://dokploy.kipavy.fr/
      check-url: http://192.168.1.149:3000/
      icon: sh:dokploy
    - title: Glance
      url: https://kipavy.fr/
      check-url: http://192.168.1.149:9998/
      icon: sh:glance
    - title: Scrutiny
      url: https://scrutiny.kipavy.fr/
      check-url: http://192.168.1.149:8087/
      icon: di:scrutiny
    - title: Immich
      url: https://immich.kipavy.fr/
      check-url: http://192.168.1.149:2283/
      icon: di:immich
    - title: qBittorrent-nox
      url: https://qbt.kipavy.fr/
      check-url: http://192.168.1.149:8091/
      icon: di:qbittorrent

- type: docker-containers
  hide-by-default: true
  containers:
    enshrouded:
      name: Enshrouded Dedicated Server
      icon: https://enshrouded.wiki.gg/images/Site-logo.png
      hide: false
    any-sync-bundle:
      name: Anytype
      icon: https://ecosystem.ipfs.tech/images/projects/icon-anytype.png
      hide: false
